INSERT INTO bears (name, age, gender, color, temperament, alive)
VALUES ("Mr. Chocolate", 7, "M", "chocolate brown", "bitter sweet", true)
INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ("Rowdy", 5,"F", "TIGER STRIPED", "sassy", false)
INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ("Tabitha", 3, "F", "Black", "tender hearted", true)
INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ("Sergeant Brown", 10, "M", "brown", "serious", false)
INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ("Melissa", 7, "F", "Grey", "sweet", true)
INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ("Grinch", 15, "M", "GREEN", "stingy", false)
INSERT INTO bears (name, age, gender, color, temperament, alive) VALUES ("Wendy", 9, "F", "red", "goofy", true)
INSERT INTO bears (color, temperament) VALUES ("brown", "mean")